<<<<<<< HEAD
export const TODO_LIST_REQUEST = 'TODO_LIST_REQUEST'
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS'
export const TODO_LIST_FAIL = 'TODO_LIST_FAIL'
=======
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
>>>>>>> 893ee60 (refactor file name)
